const ShopActionTypes = {
  FETCH_ITEMS_START : "FETCH_ITEMS_START",
  FETCH_ITEMS_SUCCESS : "FETCH_ITEMS_SUCCESS",
  FETCH_ITEMS_FAILED : "FETCH_ITEMS_FAILED",

  FETCH_SECTIONS_START : "FETCH_SECTIONS_START",
  FETCH_SECTIONS_SUCCESS : "FETCH_SECTIONS_SUCCESS",
  FETCH_SECTIONS_FAILED : "FETCH_SECTIONS_FAILED",
}

export default ShopActionTypes;