const ShopActionTypes = {
  FETCH_ITEMS_START: "FETCH_ITEMS_START",
  FETCH_ITEMS_SUCCESS: "FETCH_ITEMS_SUCCESS",
  FETCH_ITEMS_FAILED: "FETCH_ITEMS_FAILED",
  SET_ITEMS_CACHE: "SET_ITEM_CACHE",
};

export default ShopActionTypes;
