const CartActionTypes = {
  SET_CART_HIDDEN: 'SET_CART_HIDDEN',
  UPDATE_CART_START:'UPDATE_CART_START',
  UPDATE_CART_SUCCESS:'UPDATE_CART_SUCCESS',
  UPDATE_CART_FAIL:'UPDATE_CART_FAIL'


}

export default CartActionTypes;