const CartActionTypes = {
  UPDATE_CART_START: "UPDATE_CART_START",
  UPDATE_CART_SUCCESS: "UPDATE_CART_SUCCESS",
  UPDATE_CART_FAIL: "UPDATE_CART_FAIL",
  FETCH_CARTITEMS_START: "FETCH_CARTITEMS_START",
  FETCH_CARTITEMS_SUCCESS: "FETCH_CARTITEMS_SUCCESS",
  FETCH_CARTITEMS_FAIL: "FETCH_CARTITEMS_FAIL",
  SET_CART: "SET_CART",
  SET_CART_HIDDEN: "SET_CART_HIDDEN",
};

export default CartActionTypes;
