const ReviewsActionTypes = {
  UPDATE_REVIEWS_START:'UPDATE_REVIEWS_START',
  UPDATE_REVIEWS_SUCCESS:'UPDATE_REVIEWS_SUCCESS',
  UPDATE_REVIEWS_FAIL:'UPDATE_REVIEWS_FAIL'
}

export default ReviewsActionTypes;