export const UserActionTypes ={
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SET_USER_STATE: 'SET_USER_STATE',
  FETCH_USER_START: 'FETCH_USER_START',
  FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
  FETCH_USER_FAILED: 'FETCH_USER_FAILED'
}