export const UserActionTypes ={
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SIGNUP_USER_START: 'SIGNUP_USER_START',
  SIGNUP_USER_SUCCESS: 'SIGNUP_USER_SUCCESS',
  SIGNUP_USER_FAILED: 'SIGNUP_USER_FAILED'
}